### ISSUE TITLE
Attendee List

### ISSUE THREAD

**Issue by dhruvdhody** [intarchboard/draft-iab-nemops-workshop-report#1]
Need to get a merged list of workshop participants for all days from webex

**Comment by dhruvdhody** [comment]
@cindymorgan - can you help with that?

**Comment by cindymorgan** [comment]
Combined participant list from all 3 days:

Alex Huang
Alexander Clemm
Alexander PELOV
Benoit Claise
Boris Khasanov
Brad Peters (nbn)
Carsten Bormann
Chongfeng Xie
Cindy Morgan
Dan Voyer
Darren Loher
Dean Bogdanovic
Dean Bogdanović
Dhruv Dhody
Diego Lopez
Ebben Aries
Frank (Chong Feng)
Holger Keller
Ian Farrer
Jaime Jimenez
James Cumming
Janne Karvonen
Jason Sterne
Jiaming Ye
Jinming Li
John Carson
Julien Maisonneuve
Jürgen Schönwälder
Kent Watsen
Kris Lambrechts
Kristian Larsson
Laurent Ciavaglia
Laurent Toutain
Liz Flynn
Luis M. Contreras (Telefonica)
Mahesh Jethanandani
Manoj Gudi
Martin Horneffer
Matthew Bocci
Med Boucadair
Michael Mackey
Michael Richardson
Michael Scharf
Mikko Pesonen
Nacho Dominguez (Telefonica)
Naveen Achyuta
Nick Corran
Nils Warnke
Oscar Gonzalez de Dios
Paolo Lucente
Parisa foroughi
Per Andersson
Phil Shafer
Qin Wu
Qiufang Ma
Raquel Rodriguez
Reshad
Reshad Rahman
Rob Shakir
Rob Wilton
Roland Bless (KIT)
Roland Schott
Rüdiger Geib
Rui Zhuang
Ruibo han
Sabine Randriamasy
Scott Mansfield (Ericsson)
Scott Robohn
Shengnan Yue
Suresh Krishnan
Thomas Graf
Toerless Eckert
wangbo
Warren Kumari
Wes Hardaker
Wim Henderickx
Xue Yang
Y. Richard Yang
yangbo
Yisong Liu
Zhenqiang Li

**Comment by dhruvdhody** [comment]
https://github.com/intarchboard/draft-iab-nemops-workshop-report/commit/1fb27d9473ce1d84089dd61afd5a1eada743fcde

**Comment by dhruvdhody** [comment]
Thanks @cindymorgan
